dist: trusty
sudo: required

language: scala

jdk:
  - oraclejdk8
  - openjdk8

branches:
  only:
    - master

notifications:
  email: false

script:
  - ./build/mvn -q scalastyle:check test

after_success:
  # Fails because of too long tests in Travis CI
  - ./build/mvn -q cobertura:cobertura coveralls:report

